### ISSUE TITLE
Starting with 1.1.2022 this repository will be converted to Shovel only

### ISSUE THREAD

**Issue by Ash258** [shovel-org/Windows-JetBrains-Bucket#49]
- Manifests will be migrated to yaml, which will effectively make it impossible to install via scoop.
- Repository will be moved under shovel-org
- Additional tweaks to the repository and manifests

No further support for scoop users will be available.

**Comment by rashil2000** [comment]
**For Scoop users who were using this bucket:** Note that Scoop-JetBrains is no longer an official/known bucket. See https://github.com/ScoopInstaller/Scoop#known-application-buckets. Use the Main and Extras buckets to install your favorite JetBrains tools. Open a PR there if any application is missing.

**Comment by xfournet** [comment]
what is Shovel ?
